# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-23 04:14
from __future__ import unicode_literals

import bdo.models.guild
import bdo.models.mixins
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('bdo', '0001_initial'), ('bdo', '0002_auto_20171230_0117'), ('bdo', '0003_auto_20171230_1541'), ('bdo', '0004_auto_20171230_2052'), ('bdo', '0005_auto_20171230_2054'), ('bdo', '0006_war_note'), ('bdo', '0007_auto_20180113_1817'), ('bdo', '0008_auto_20180113_1818'), ('bdo', '0009_auto_20180113_1822'), ('bdo', '0010_auto_20180113_1827'), ('bdo', '0011_auto_20180113_2310'), ('bdo', '0012_auto_20180114_0021'), ('bdo', '0013_auto_20180114_2321'), ('bdo', '0014_auto_20180118_0430'), ('bdo', '0015_auto_20180118_0432'), ('bdo', '0016_auto_20180121_2206'), ('bdo', '0017_auto_20180124_0253'), ('bdo', '0018_auto_20180203_1616'), ('bdo', '0019_auto_20180203_1757'), ('bdo', '0020_auto_20180218_0414'), ('bdo', '0021_auto_20180225_2256'), ('bdo', '0022_auto_20180309_0254'), ('bdo', '0023_auto_20180309_0302'), ('bdo', '0024_profile_discord_id'), ('bdo', '0025_auto_20180316_0023'), ('bdo', '0026_auto_20180316_0024'), ('bdo', '0027_auto_20180323_0125'), ('bdo', '0028_profile_auto_sign_up')]

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField()),
                ('ap', models.IntegerField()),
                ('aap', models.IntegerField()),
                ('dp', models.IntegerField()),
                ('is_main', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(models.Model, bdo.models.mixins.UserPermissionMixin),
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.ImageField(upload_to='')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Guild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo_url', models.URLField()),
                ('description', models.TextField(default='')),
                ('settings', django.contrib.postgres.fields.jsonb.JSONField()),
                ('discord_id', models.CharField(max_length=75)),
                ('discord_roles', django.contrib.postgres.fields.jsonb.JSONField()),
                ('discord_invite_url', models.CharField(max_length=255, null=True)),
                ('guild_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='GuildRole',
            fields=[
                ('group_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.Group')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='')),
                ('custom_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_guild_roles', to='bdo.Guild')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('auth.group',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('preferences', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
            bases=(models.Model, bdo.models.mixins.UserPermissionMixin),
        ),
        migrations.CreateModel(
            name='War',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('victory', models.BooleanField()),
                ('setup', django.contrib.postgres.fields.jsonb.JSONField(default={'call_signs': {}, 'party': {}, 'platoon': {}, 'roles': {}})),
                ('is_complete', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WarAttendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdo.Character')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.Profile')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.War')),
                ('is_attending', models.BooleanField(default=False)),
                ('extra', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('setup', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('note', models.CharField(blank=True, max_length=512, null=True)),
                ('slot_number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WarNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tier', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Territory')])),
                ('war_day', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=1)),
                ('war_channel', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WarTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groups', django.contrib.postgres.fields.jsonb.JSONField(default={'call_signs': {}, 'party': {}, 'platoon': {}})),
                ('roles', django.contrib.postgres.fields.jsonb.JSONField(default={})),
            ],
        ),
        migrations.AddField(
            model_name='war',
            name='attendees',
            field=models.ManyToManyField(through='bdo.WarAttendance', to='bdo.Profile'),
        ),
        migrations.AddField(
            model_name='war',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.Guild'),
        ),
        migrations.AddField(
            model_name='war',
            name='node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdo.WarNode'),
        ),
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.CharacterClass'),
        ),
        migrations.AddField(
            model_name='character',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.Profile'),
        ),
        migrations.AlterUniqueTogether(
            name='warattendance',
            unique_together=set([('user_profile', 'war')]),
        ),
        migrations.AddField(
            model_name='war',
            name='note',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.RemoveField(
            model_name='war',
            name='setup',
        ),
        migrations.CreateModel(
            name='WarArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('region', models.IntegerField(choices=[(0, 'Balenos'), (1, 'Serendia'), (2, 'Calpheon'), (3, 'Mediah'), (4, 'Valencia')])),
            ],
        ),
        migrations.AddField(
            model_name='warnode',
            name='area',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bdo.WarArea'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WarCallSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_signs', to='bdo.War')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='WarRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('custom_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdo.Guild')),
            ],
        ),
        migrations.CreateModel(
            name='WarTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.IntegerField(choices=[('PLATOON', 0), ('PARTY', 1)])),
                ('slot_setup', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, null=True)),
                ('default_role', models.ForeignKey(on_delete=models.SET(bdo.models.guild.WarRole.GET_DEFAULT_ROLE), to='bdo.WarRole')),
                ('war', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.War')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bdo.Profile'),
        ),
        migrations.AlterField(
            model_name='warnode',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='warnode',
            unique_together=set([('war_day', 'area')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_roles',
            field=models.ManyToManyField(blank=True, to='bdo.WarRole'),
        ),
        migrations.AddField(
            model_name='warattendance',
            name='call_signs',
            field=models.ManyToManyField(to='bdo.WarCallSign'),
        ),
        migrations.AddField(
            model_name='warattendance',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bdo.WarTeam'),
        ),
        migrations.RemoveField(
            model_name='warattendance',
            name='extra',
        ),
        migrations.RemoveField(
            model_name='warattendance',
            name='setup',
        ),
        migrations.AlterUniqueTogether(
            name='warattendance',
            unique_together=set([('user_profile', 'war'), ('war', 'team')]),
        ),
        migrations.AlterModelOptions(
            name='warattendance',
            options={'ordering': ('id',)},
        ),
        migrations.AlterModelOptions(
            name='warrole',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='warrole',
            name='custom_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='custom_war_roles', to='bdo.Guild'),
        ),
        migrations.AlterUniqueTogether(
            name='warrole',
            unique_together=set([('name', 'custom_for')]),
        ),
        migrations.CreateModel(
            name='GuildMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.RemoveField(
            model_name='guild',
            name='guild_master',
        ),
        migrations.AddField(
            model_name='guildmember',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='bdo.Guild'),
        ),
        migrations.AddField(
            model_name='guildmember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.GuildRole'),
        ),
        migrations.AddField(
            model_name='guildmember',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membership', to='bdo.Profile'),
        ),
        migrations.AddField(
            model_name='guild',
            name='members',
            field=models.ManyToManyField(related_name='guilds', through='bdo.GuildMember', to='bdo.Profile'),
        ),
        migrations.RemoveField(
            model_name='warattendance',
            name='call_signs',
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='bdo.War'),
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='is_attending',
            field=models.IntegerField(choices=[('ATTENDING', 0), ('NOT_ATTENDING', 1), ('UNDECIDED', 2)]),
        ),
        migrations.AlterUniqueTogether(
            name='warattendance',
            unique_together=set([('user_profile', 'war', 'team')]),
        ),
        migrations.CreateModel(
            name='WarTeamSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='warcallsign',
            name='members',
            field=models.ManyToManyField(blank=True, to='bdo.WarAttendance'),
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_set', to='bdo.War'),
        ),
        migrations.AlterField(
            model_name='warcallsign',
            name='war',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.War'),
        ),
        migrations.RemoveField(
            model_name='warattendance',
            name='slot_number',
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='is_attending',
            field=models.IntegerField(choices=[(0, 'ATTENDING'), (1, 'NOT_ATTENDING'), (2, 'UNDECIDED')], default=2),
        ),
        migrations.RemoveField(
            model_name='warattendance',
            name='team',
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='is_attending',
            field=models.IntegerField(choices=[(0, 'ATTENDING'), (1, 'NOT_ATTENDING'), (2, 'UNDECIDED'), (3, 'NO_SHOW')], default=2),
        ),
        migrations.AlterUniqueTogether(
            name='warattendance',
            unique_together=set([('user_profile', 'war')]),
        ),
        migrations.AddField(
            model_name='warteamslot',
            name='attendee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='bdo.WarAttendance'),
        ),
        migrations.AddField(
            model_name='warteamslot',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bdo.WarTeam'),
        ),
        migrations.AddField(
            model_name='warteam',
            name='members',
            field=models.ManyToManyField(through='bdo.WarTeamSlot', to='bdo.WarAttendance'),
        ),
        migrations.CreateModel(
            name='WarStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_post', models.IntegerField(default=0)),
                ('fort', models.IntegerField(default=0)),
                ('gate', models.IntegerField(default=0)),
                ('help', models.IntegerField(default=0)),
                ('mount', models.IntegerField(default=0)),
                ('placed_objects', models.IntegerField(default=0)),
                ('guild_master', models.IntegerField(default=0)),
                ('officer', models.IntegerField(default=0)),
                ('member', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('siege_weapons', models.IntegerField(default=0)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bdo.WarAttendance')),
            ],
        ),
        migrations.AlterField(
            model_name='warteam',
            name='type',
            field=models.IntegerField(choices=[(0, 'PLATOON'), (1, 'PARTY')]),
        ),
        migrations.RemoveField(
            model_name='war',
            name='is_complete',
        ),
        migrations.RemoveField(
            model_name='war',
            name='victory',
        ),
        migrations.AddField(
            model_name='war',
            name='outcome',
            field=models.IntegerField(blank=True, choices=[(0, 'WIN'), (1, 'LOSS'), (2, 'STALEMATE')], null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='user_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_set', to='bdo.Profile'),
        ),
        migrations.AlterModelOptions(
            name='warnode',
            options={'ordering': ('name',)},
        ),
        migrations.RemoveField(
            model_name='guild',
            name='discord_invite_url',
        ),
        migrations.AlterUniqueTogether(
            name='guildmember',
            unique_together=set([('guild', 'user')]),
        ),
        migrations.AlterModelOptions(
            name='guild',
            options={'ordering': ('id',), 'permissions': (('view_overview', 'Can see overview page'), ('view_members', 'Can see members page'), ('view_history', 'Can see history page'), ('view_war', 'Can see war page'), ('view_activity_log', 'Can see guild activity log'), ('change_guild_info', 'Can edit basic guild information'), ('change_guild_integration', 'Can edit guild Discord integration'), ('change_member_attendance', "Can edit member's attendance"), ('change_my_attendance', 'Can edit own attendance'), ('change_war', 'Can modify war setup'), ('add_war', 'Can start a pending war'), ('delete_war', 'Can delete a pending war'))},
        ),
        migrations.RemoveField(
            model_name='guild',
            name='settings',
        ),
        migrations.AddField(
            model_name='guild',
            name='discord_members',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
        migrations.AddField(
            model_name='profile',
            name='discord_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='availability',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'Friday': 2, 'Monday': 2, 'Saturday': 2, 'Sunday': 2, 'Thursday': 2, 'Tuesday': 2, 'Wednesday': 2}),
        ),
        migrations.AddField(
            model_name='profile',
            name='auto_sign_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('id', 'user')]),
        ),
        migrations.AlterModelOptions(
            name='guild',
            options={'ordering': ('id',), 'permissions': (('view_overview', 'Can see overview page'), ('view_members', 'Can see members page'), ('view_history', 'Can see history page'), ('view_war', 'Can see war page'), ('view_activity_log', 'Can see guild activity log'), ('change_guild_info', 'Can edit basic guild information'), ('change_guild_integration', 'Can edit guild Discord integration'), ('change_member_attendance', "Can edit member's attendance"), ('change_my_attendance', 'Can edit own attendance'), ('change_war', 'Can modify war setup'), ('add_war', 'Can start a pending war'), ('delete_war', 'Can delete a pending war'), ('manage_team', 'Can create, edit or delete teams'), ('manage_call_sign', 'Can create, edit or delete call signs'))},
        ),
        migrations.AlterField(
            model_name='warattendance',
            name='is_attending',
            field=models.IntegerField(choices=[(0, 'ATTENDING'), (1, 'NOT_ATTENDING'), (2, 'UNDECIDED'), (3, 'NO_SHOW'), (4, 'LATE')], default=2),
        ),
    ]
