# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='family_name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
