# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 05:00
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('bdo', '0002_make_family_name_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'GUILD_CREATE'), (2, 'GUILD_UPDATE'), (3, 'GUILD_UPDATE_INTEGRATION'), (4, 'GUILD_DELETE'), (5, 'WAR_CREATE'), (6, 'WAR_UPDATE'), (7, 'WAR_DELETE'), (8, 'WAR_END'), (9, 'ATTENDANCE_UPDATE')])),
                ('object_id', models.PositiveIntegerField()),
                ('target_description', models.CharField(blank=True, max_length=255, null=True)),
                ('extras', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('actor_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.Profile')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('guild', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bdo.Guild')),
            ],
        ),
        migrations.AlterModelOptions(
            name='war',
            options={'ordering': ('-date', 'id')},
        ),
    ]
