# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-31 06:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0004_activity_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
