# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-01 00:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0005_allow_null_target'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ('-date', 'id')},
        ),
        migrations.AddField(
            model_name='guild',
            name='discord_notifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'war_cancel': True, 'war_create': True, 'war_end': True}),
        ),
        migrations.AddField(
            model_name='guild',
            name='discord_webhook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='warnode',
            name='tier',
            field=models.IntegerField(choices=[(1, 'Tier 1'), (2, 'Tier 2'), (3, 'Tier 3'), (4, 'Tier 4')]),
        ),
    ]
