# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-02 01:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0006_add_new_discord_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='discord_webhook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
