# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 02:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0009_add_pre_war_warning_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AggregatedGuildMemberWarStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_post', models.IntegerField(default=0)),
                ('fort', models.IntegerField(default=0)),
                ('gate', models.IntegerField(default=0)),
                ('help', models.IntegerField(default=0)),
                ('mount', models.IntegerField(default=0)),
                ('placed_objects', models.IntegerField(default=0)),
                ('guild_master', models.IntegerField(default=0)),
                ('officer', models.IntegerField(default=0)),
                ('member', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('siege_weapons', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('kdr', models.FloatField(default=0.0)),
                ('wars_attended', models.IntegerField(default=0)),
                ('wars_unavailable', models.IntegerField(default=0)),
                ('wars_missed', models.IntegerField(default=0)),
                ('guild', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.Guild')),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bdo.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='AggregatedGuildWarStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_post', models.IntegerField(default=0)),
                ('fort', models.IntegerField(default=0)),
                ('gate', models.IntegerField(default=0)),
                ('help', models.IntegerField(default=0)),
                ('mount', models.IntegerField(default=0)),
                ('placed_objects', models.IntegerField(default=0)),
                ('guild_master', models.IntegerField(default=0)),
                ('officer', models.IntegerField(default=0)),
                ('member', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('siege_weapons', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('kdr', models.FloatField(default=0.0)),
                ('guild', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='guild_stats', to='bdo.Guild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AggregatedUserWarStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_post', models.IntegerField(default=0)),
                ('fort', models.IntegerField(default=0)),
                ('gate', models.IntegerField(default=0)),
                ('help', models.IntegerField(default=0)),
                ('mount', models.IntegerField(default=0)),
                ('placed_objects', models.IntegerField(default=0)),
                ('guild_master', models.IntegerField(default=0)),
                ('officer', models.IntegerField(default=0)),
                ('member', models.IntegerField(default=0)),
                ('death', models.IntegerField(default=0)),
                ('siege_weapons', models.IntegerField(default=0)),
                ('total_kills', models.IntegerField(default=0)),
                ('kdr', models.FloatField(default=0.0)),
                ('wars_attended', models.IntegerField(default=0)),
                ('wars_unavailable', models.IntegerField(default=0)),
                ('wars_missed', models.IntegerField(default=0)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_stats', to='bdo.Profile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='aggregatedguildmemberwarstats',
            unique_together=set([('guild', 'user_profile')]),
        ),
    ]
