# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-26 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0012_add_renege_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.IntegerField(choices=[(1, 'GUILD_CREATE'), (2, 'GUILD_UPDATE'), (3, 'GUILD_UPDATE_INTEGRATION'), (4, 'GUILD_DELETE'), (5, 'WAR_CREATE'), (6, 'WAR_UPDATE'), (7, 'WAR_DELETE'), (8, 'WAR_END'), (9, 'ATTENDANCE_UPDATE'), (10, 'WAR_STAT_CREATE'), (11, 'WAR_STAT_DELETE'), (12, 'WAR_STAT_UPDATE')]),
        ),
        migrations.AlterField(
            model_name='aggregatedguildmemberwarstats',
            name='guild',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregatedmemberstats', to='bdo.Guild'),
        ),
        migrations.AlterField(
            model_name='aggregatedguildmemberwarstats',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aggregatedmemberstats', to='bdo.Profile'),
        ),
    ]
