# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-27 21:22
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0013_add_new_activities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guild',
            name='discord_roles',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'member': None, 'mercenary': None, 'officer': None, 'quartermaster': None}),
        ),
    ]
