# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-03 22:14
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0014_add_default_discord_role_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='npc_renown',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
