# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-01 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0015_profile_npc_renown'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('node_war_start_time', models.TimeField()),
                ('node_war_end_time', models.TimeField()),
                ('conquest_war_start_time', models.TimeField()),
                ('conquest_war_end_time', models.TimeField()),
            ],
        ),
    ]
