# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-01 20:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bdo', '0016_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bdo.Region'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bdo.Region'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='guild',
            unique_together=set([('name', 'region')]),
        ),
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('user', 'region')]),
        ),
    ]
