# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-14 18:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


def migrate_existing_guilds(apps, schema_editor):
    # Existing guilds with that option should have a default of 30min before.
    Guild = apps.get_model('bdo', 'Guild')
    Guild.objects.filter(discord_notifications__war_start_warning=True).update(discord_war_reminder=30)


class Migration(migrations.Migration):

    dependencies = [
        ('bdo', '0018_region_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='guild',
            name='discord_war_reminder',
            field=models.IntegerField(default=-1, choices=[(60, '60min before'), (30, '30min before'), (15, '15min before'), (-1, 'Disabled')]),
        ),
        migrations.AlterField(
            model_name='guild',
            name='discord_notifications',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={'war_cancel': True, 'war_create': True, 'war_end': True}),
        ),
        migrations.RunPython(migrate_existing_guilds),
    ]
